<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [1]:

import numpy as np
import os
import sys

In [1]:
import tensorflow

D:\Anaconda\envs\proj9\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\Anaconda\envs\proj9\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\Anaconda\envs\proj9\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\Anaconda\envs\proj9\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type

In [2]:
from sklearn.model_selection import train_test_split


In [4]:
from PIL import Image
import PIL

In [21]:
#import tensorflow
from tensorflow.python.keras.preprocessing import image

In [5]:
from tensorflow.python.keras import backend as K
from tensorflow.python.keras.layers import Input, Conv2D, MaxPooling2D, concatenate, UpSampling2D
from tensorflow.python.keras.optimizers import Adadelta, Nadam
from tensorflow.python.keras.models import Model, load_model
from tensorflow.python.keras.utils import multi_gpu_model, plot_model
from tensorflow.python.keras.callbacks import TensorBoard, ModelCheckpoint, EarlyStopping, ReduceLROnPlateau
from tensorflow.python.keras.preprocessing import image

In [2]:
from tensorflow.python.keras.losses import binary_crossentropy
from tensorflow.python.keras.utils import Sequence
from tensorflow.python.keras.callbacks import Callback

In [32]:
from dilatednet import DilatedNet
from multiclassunet import Unet

In [26]:
import cv2


In [20]:
import matplotlib.pyplot as plt

In [16]:
import sys
from PIL import Image
sys.modules['Image'] = Image 

In [18]:
from PIL import Image
print(Image.__file__)

D:\Anaconda\envs\proj9\lib\site-packages\PIL\Image.py


In [19]:
import Image
print(Image.__file__)

D:\Anaconda\envs\proj9\lib\site-packages\PIL\Image.py


In [6]:
dirname = os.getcwd()
name = 'gtFine/train/hamburg/hamburg_000000_000042_gtFine_labelIds.png' 
filename = os.path.join(dirname, name)
print(filename)

C:\Users\favre\projet_9\gtFine/train/hamburg/hamburg_000000_000042_gtFine_labelIds.png


In [7]:
img = image.img_to_array(image.load_img(filename, grayscale=True, target_size=(256, 256)))

D:\Anaconda\envs\proj9\lib\site-packages\keras_preprocessing\image\utils.py:107: UserWarning: grayscale is deprecated. Please use color_mode = "grayscale"
  warnings.warn('grayscale is deprecated. Please use '


In [10]:
#conda env update --file env-p9.yml  --prune

In [8]:
img

array([[[ 3.],
        [ 3.],
        [ 3.],
        ...,
        [ 3.],
        [ 3.],
        [ 3.]],

       [[ 3.],
        [ 2.],
        [21.],
        ...,
        [ 2.],
        [ 2.],
        [ 3.]],

       [[ 3.],
        [ 2.],
        [21.],
        ...,
        [ 2.],
        [ 2.],
        [ 3.]],

       ...,

       [[ 3.],
        [ 2.],
        [ 2.],
        ...,
        [ 1.],
        [ 1.],
        [ 3.]],

       [[ 3.],
        [ 2.],
        [ 2.],
        ...,
        [ 1.],
        [ 1.],
        [ 3.]],

       [[ 3.],
        [ 3.],
        [ 3.],
        ...,
        [ 3.],
        [ 3.],
        [ 3.]]], dtype=float32)

In [9]:
img2 = np.squeeze(img)

In [10]:
print(img2)

[[ 3.  3.  3. ...  3.  3.  3.]
 [ 3.  2. 21. ...  2.  2.  3.]
 [ 3.  2. 21. ...  2.  2.  3.]
 ...
 [ 3.  2.  2. ...  1.  1.  3.]
 [ 3.  2.  2. ...  1.  1.  3.]
 [ 3.  3.  3. ...  3.  3.  3.]]


In [11]:
img.shape

(256, 256, 1)

In [12]:
img2.shape

(256, 256)

In [13]:
labels = np.unique(img)
labels

array([ 1.,  2.,  3.,  4.,  5.,  7.,  8., 11., 12., 13., 15., 17., 19.,
       20., 21., 22., 23., 24., 25., 26., 27., 29., 32., 33.],
      dtype=float32)

In [36]:
idx = np.random.randint(0, 100, 3)
idx

array([91, 57,  6])

In [14]:
#division of labelling
cats = {'void': [0, 1, 2, 3, 4, 5, 6],
 'flat': [7, 8, 9, 10],
 'construction': [11, 12, 13, 14, 15, 16],
 'object': [17, 18, 19, 20],
 'nature': [21, 22],
 'sky': [23],
 'human': [24, 25],
 'vehicle': [26, 27, 28, 29, 30, 31, 32, 33, -1]}

In [3]:
#name of directory
image_dir = 'sample/sample_photo'
mask_dir = 'sample/sample_mask'
mask = 'labelIds'

In [4]:
#extract list of pictures 
image_list = []
for root, dirs, files in os.walk(image_dir):
    for name in files:
        image_list.append(os.path.join(root, name))

#extract mask with label
mask_list_l = []
for root, dirs, files in os.walk(mask_dir):
    for name in files:
        mask_list_l.append(os.path.join(root, name))

mask_list = [m for m in mask_list_l if mask in m]

print(len(image_list), len(mask_list))

174 174


In [3]:
import shutil

image_dir = 'sample/sample_photo'
mask_dir = 'sample/sample_mask'
mask = '_labelIds'

new_image_dir= 'test2/image'
new_mask_dir= 'test2/mask'
os.makedirs(new_image_dir, exist_ok=True)
os.makedirs(new_mask_dir, exist_ok=True)
reduction = '_leftImg8bit'

#extract list of pictures 
image_list = []
for root, dirs, files in os.walk(image_dir):
    for name in files:        
        old_path = os.path.join(root, name)
        new_name = name.replace('_leftImg8bit', '')        
        new_path = os.path.join(new_mask_dir, new_name)
        if not os.path.exists(new_path):
            shutil.copy(old_path, new_path)
        
        image_list.append(new_path)
        

mask_list = []
for root, dirs, files in os.walk(mask_dir):
    for name in files:
        if mask in name:
            old_path = os.path.join(root, name)
            new_name = name.replace('_gtFine_labelIds', '')        
            new_path = os.path.join(new_image_dir, new_name)
            if not os.path.exists(new_path):
                shutil.copy(old_path, new_path)

            mask_list.append(new_path)

In [21]:
nom = 'aachen_000000_000019_leftImg8bit.png'
new = nom.replace('_leftImg8bit', '')
print(mask_list[1])

sample/sample_mask\aachen\aachen_000001_000019_gtFine_labelIds.png


In [41]:
#parameters
batch_size = 2
samples = 50000
steps = samples//batch_size
img_height, img_width = 256, 256
classes = 8
filters_n = 64

In [31]:
#test de getitem

#make a array of length batch size containing random position of photo
idx = np.random.randint(0, 2975, batch_size)
for i in idx:
    #import to array a normalize image
    _image = image.img_to_array(image.load_img(f'{image_list[i]}', target_size=(img_height, img_width)))/255.
    #import to array the mask
    img = image.img_to_array(image.load_img(f'{mask_list[i]}', grayscale=True, target_size=(img_height, img_width)))

D:\Anaconda\envs\proj9\lib\site-packages\keras_preprocessing\image\utils.py:107: UserWarning: grayscale is deprecated. Please use color_mode = "grayscale"
  warnings.warn('grayscale is deprecated. Please use '


In [68]:
def plot_image(test_image, test_mask):
    fig = plt.figure(figsize=(15, 15))
    ax = fig.add_subplot(1, 2, 1)
    ax.set_title('Image')
    ax.imshow(test_image)

    ax1 = fig.add_subplot(1, 2, 2)
    ax1.set_title('GT_Mask')
    ax1.imshow(test_mask)

In [70]:
labels = np.unique(img)
labels

array([ 1.,  3.,  4.,  7.,  9., 11., 13., 17., 21., 23., 26.],
      dtype=float32)

In [76]:
img = np.squeeze(img)
#create empty tensor dimension img img and 1 per category (8)
mask = np.zeros((img.shape[0], img.shape[1], 8))
#iterate through sub category
for i in range(-1, 34):
    if i in cats['void']:
        mask[:,:,0] = np.logical_or(mask[:,:,0],(img==i))
    elif i in cats['flat']:
        mask[:,:,1] = np.logical_or(mask[:,:,1],(img==i))
    elif i in cats['construction']:
        mask[:,:,2] = np.logical_or(mask[:,:,2],(img==i))
    elif i in cats['object']:
        mask[:,:,3] = np.logical_or(mask[:,:,3],(img==i))
    elif i in cats['nature']:
        mask[:,:,4] = np.logical_or(mask[:,:,4],(img==i))
    elif i in cats['sky']:
        mask[:,:,5] = np.logical_or(mask[:,:,5],(img==i))
        print(mask[:,:,5])
    elif i in cats['human']:
        mask[:,:,6] = np.logical_or(mask[:,:,6],(img==i))
    elif i in cats['vehicle']:
        mask[:,:,7] = np.logical_or(mask[:,:,7],(img==i))
        
mask = np.resize(mask,(img_height*img_width, 8))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [75]:
mask

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [49]:
class seg_gen(Sequence):
    def __init__(self, x_set, y_set, batch_size):
        self.x, self.y = x_set, y_set
        self.batch_size = batch_size

    def __len__(self):
        return int(np.ceil(len(self.x) / float(self.batch_size)))

    def __getitem__(self, idx):
        #make a array of length batch size containing random position of photo
        idx = np.random.randint(0, 10, batch_size)
        batch_x, batch_y = [], []
        drawn = 0
        
        for i in idx:
            #import original image /255 to normalize and avoid big number for compute power
            _image = image.img_to_array(image.load_img(f'{image_list[i]}', target_size=(img_height, img_width)))/255.
            #import mask
            img = image.img_to_array(image.load_img(f'{mask_list[i]}', grayscale=True, target_size=(img_height, img_width)))
            #assess number of different label
            labels = np.unique(img)
            #ignore picture withtout features
            if len(labels) < 3:
                idx = np.random.randint(0, 50000, batch_size-drawn)
                continue
            img = np.squeeze(img)
            #create a tensor of dimension image with one plan for each category
            mask = np.zeros((img.shape[0], img.shape[1], 8))
            for i in range(-1, 34):
                if i in cats['void']:
                    mask[:,:,0] = np.logical_or(mask[:,:,0],(img==i))
                elif i in cats['flat']:
                    mask[:,:,1] = np.logical_or(mask[:,:,1],(img==i))
                elif i in cats['construction']:
                    mask[:,:,2] = np.logical_or(mask[:,:,2],(img==i))
                elif i in cats['object']:
                    mask[:,:,3] = np.logical_or(mask[:,:,3],(img==i))
                elif i in cats['nature']:
                    mask[:,:,4] = np.logical_or(mask[:,:,4],(img==i))
                elif i in cats['sky']:
                    mask[:,:,5] = np.logical_or(mask[:,:,5],(img==i))
                elif i in cats['human']:
                    mask[:,:,6] = np.logical_or(mask[:,:,6],(img==i))
                elif i in cats['vehicle']:
                    mask[:,:,7] = np.logical_or(mask[:,:,7],(img==i))
            mask = np.resize(mask,(img_height*img_width, 8))
            batch_y.append(mask)
            batch_x.append(_image)
            drawn += 1
        return np.array(batch_x), np.array(batch_y)

In [33]:
def dice_coeff(y_true, y_pred):
    smooth = 1.
    y_true_f = K.flatten(y_true)
    y_pred_f = K.flatten(y_pred)
    intersection = K.sum(y_true_f * y_pred_f)
    score = (2. * intersection + smooth) / (K.sum(y_true_f) + K.sum(y_pred_f) + smooth)
    return score

def dice_loss(y_true, y_pred):
    loss = 1 - dice_coeff(y_true, y_pred)
    return loss

def total_loss(y_true, y_pred):
    loss = binary_crossentropy(y_true, y_pred) + (3*dice_loss(y_true, y_pred))
    return loss

In [52]:
unet = DilatedNet(256, 256, 8,use_ctx_module=True, bn=True)

. . . . .Building DilatedNet. . . . .
. . . . .Building network successful. . . . .


**multi_gpu_model**  
Specifically, this function implements single-machine multi-GPU data parallelism. It works in the following way:

Divide the model's input(s) into multiple sub-batches.
Apply a model copy on each sub-batch. Every model copy is executed on a dedicated GPU.
Concatenate the results (on CPU) into one big batch.
E.g. if your batch_size is 64 and you use gpus=2, then we will divide the input into 2 sub-batches of 32 samples, process each sub-batch on one GPU, then return the full batch of 64 processed samples.

This induces quasi-linear speedup on up to 8 GPUs.

In [35]:

p_unet = multi_gpu_model(unet, 4)

ValueError: To call `multi_gpu_model` with `gpus=4`, we expect the following devices to be available: ['/cpu:0', '/gpu:0', '/gpu:1', '/gpu:2', '/gpu:3']. However this machine only has: ['/cpu:0']. Try reducing `gpus`.

In [53]:
unet.compile(optimizer='adam', loss='categorical_crossentropy', metrics=[dice_coeff, 'accuracy'])

In [37]:
tb = TensorBoard(log_dir='logs', write_graph=True)

In [38]:
mc = ModelCheckpoint(mode='max', filepath='models/pdilated.h5', monitor='acc', save_best_only='True', save_weights_only='True', verbose=1)

In [39]:
es = EarlyStopping(mode='max', monitor='acc', patience=6, verbose=1)

In [57]:
callbacks = [tb, mc, es]

In [55]:
#vizualize every callback
vis = visualize()

In [50]:
train_gen = seg_gen(image_list[:10], mask_list[:10], batch_size)

In [58]:
unet.fit_generator(train_gen, epochs=5, callbacks=callbacks)

Epoch 1/5
4/5 [=======================>......] - ETA: 14s - loss: 1.5345 - dice_coeff: 0.4493 - acc: 0.5204

D:\Anaconda\envs\proj9\lib\site-packages\keras_preprocessing\image\utils.py:107: UserWarning: grayscale is deprecated. Please use color_mode = "grayscale"
  warnings.warn('grayscale is deprecated. Please use '



Epoch 00001: acc improved from -inf to 0.52880, saving model to models/pdilated.h5
5/5 [==============================] - 75s 15s/step - loss: 1.5284 - dice_coeff: 0.4615 - acc: 0.5288
Epoch 2/5
4/5 [=======================>......] - ETA: 12s - loss: 0.8751 - dice_coeff: 0.6292 - acc: 0.6915
Epoch 00002: acc improved from 0.52880 to 0.68309, saving model to models/pdilated.h5
5/5 [==============================] - 63s 13s/step - loss: 0.8803 - dice_coeff: 0.6253 - acc: 0.6831
Epoch 3/5
4/5 [=======================>......] - ETA: 12s - loss: 0.7934 - dice_coeff: 0.6251 - acc: 0.7002
Epoch 00003: acc improved from 0.68309 to 0.70419, saving model to models/pdilated.h5
5/5 [==============================] - 67s 13s/step - loss: 0.7846 - dice_coeff: 0.6253 - acc: 0.7042
Epoch 4/5
4/5 [=======================>......] - ETA: 13s - loss: 0.8010 - dice_coeff: 0.6012 - acc: 0.6472
Epoch 00004: acc did not improve from 0.70419
5/5 [==============================] - 67s 13s/step - loss: 0.8032 -

In [54]:
class visualize(Callback):
    def on_epoch_end(self, epoch, logs):
        print(f'\nGenerating output at epoch : {epoch}')
        i = 567
        img = image.img_to_array(image.load_img(f'{image_list[i]}'))/255.    
        dims = img.shape
        x = cv2.resize(img, (256, 256))
        x = np.float32(x)/255.
        z = unet.predict(np.expand_dims(x, axis=0))
        z = np.squeeze(z)
        z = z.reshape(256, 256, 8)
        z = cv2.resize(z, (dims[1], dims[0]))
        y = np.argmax(z, axis=2)
        
        construction = np.zeros_like(y)
        human = np.zeros_like(y)
        vehicle = np.zeros_like(y)
        construction[y==2] = 255.
        human[y==6] = 255.
        vehicle[y==7] = 255.
        
        result = img.copy()
        alpha = 0.4
        img[:,:,1] = construction
        img[:,:,2] = vehicle 
        img[:,:,0] = human

        cv2.addWeighted(img, alpha, result, 1-alpha, 0, result)
        cv2.imwrite(f'outputs/{epoch}.png', cv2.cvtColor(result, cv2.COLOR_RGB2BGR))
        print('Wrote file to disk')

In [7]:
%load_ext tensorboard

In [9]:
%tensorboard --logdir logs/train

Reusing TensorBoard on port 6006 (pid 2432), started 0:01:55 ago. (Use '!kill 2432' to kill it.)

In [2]:
import Augmentor

In [4]:
print(os.path.abspath('test'))

C:\Users\favre\projet_9\test


In [5]:
new_image_dir = 'test/image'
new_mask_dir = 'test/mask'
output_dir = os.path.abspath('test/augmented')

#build augmentor pipeline
p = Augmentor.Pipeline(new_image_dir, output_dir)

#add groud truth for pair modification
p.ground_truth(new_mask_dir)

#add operation
p.rotate(probability=1, max_left_rotation=10, max_right_rotation=10)
p.flip_left_right(probability=0.5)
p.zoom_random(probability=0.5, percentage_area=0.8)
p.skew(probability=0.5, magnitude=0.5)
p.skew_tilt(probability=0.5, magnitude=0.5)
p.random_distortion(probability=0.5,grid_height=4, grid_width=4, magnitude=4)
p.shear(probability=0.5, max_shear_left=10, max_shear_right=10)
p.gaussian_distortion(probability=0.5, corner='bell', method='in', grid_height=4, grid_width=4, magnitude=4)
p.skew_top_bottom(probability=0.5, magnitude=.5)
p.skew_left_right(probability=0.5, magnitude=.5)
p.skew_corner(probability=0.5, magnitude=.5)
p.resize(probability=1,width=256, height=256)

print('start sampling')
p.sample(15)

Initialised with 6 image(s) found.
Output directory set to C:\Users\favre\projet_9\test\augmented.

6 ground truth image(s) found.
start sampling


Processing <PIL.Image.Image image mode=L size=256x256 at 0x24C239E6B08>: 100%|███| 15/15 [00:04<00:00,  3.25 Samples/s]


In [7]:
import os

image_dir = 'test/image'
mask_dir = 'test/mask'
aug_dir = 'test/augmented'

image_list = []
mask_list = []

for root, dirs, files in os.walk(mask_dir):
    for name in files:
        mask_list.append(os.path.join(root, name))
        
for root, dirs, files in os.walk(image_dir):
    for name in files:
        image_list.append(os.path.join(root, name))

for root, dirs, files in os.walk(aug_dir):
    for name in files:
        if 'groundtruth' in name:
            mask_list.append(os.path.join(root, name))
        else:
            image_list.append(os.path.join(root, name))





In [8]:
len(mask_list)

21

In [9]:
len(image_list)

21

In [12]:
for item in mask_list:
    print(item,'\n')

test/mask\aachen_000000_000019.png 

test/mask\aachen_000001_000019.png 

test/mask\aachen_000002_000019.png 

test/mask\aachen_000003_000019.png 

test/mask\aachen_000004_000019.png 

test/mask\aachen_000005_000019.png 

test/augmented\_groundtruth_(1)_image_aachen_000000_000019.png_6ffb9fec-f80a-4a02-9e34-d36065d5b5ff.png 

test/augmented\_groundtruth_(1)_image_aachen_000001_000019.png_011653eb-8368-4895-90f6-ba0ed7dbeed8.png 

test/augmented\_groundtruth_(1)_image_aachen_000001_000019.png_56e8642c-ec1f-4c7d-89e5-d931d8ce05f3.png 

test/augmented\_groundtruth_(1)_image_aachen_000001_000019.png_90464c97-3175-4b4b-be49-441e52fcbb03.png 

test/augmented\_groundtruth_(1)_image_aachen_000001_000019.png_9d45ce92-457c-4e92-b147-af0606a91cdf.png 

test/augmented\_groundtruth_(1)_image_aachen_000001_000019.png_fa216f30-27e3-4c4e-a749-1baa59af743e.png 

test/augmented\_groundtruth_(1)_image_aachen_000002_000019.png_7c4ec104-c8ef-4fda-af2a-a94174c3955b.png 

test/augmented\_groundtruth_(1)_imag

In [13]:
for item in image_list:
    print(item,'\n')

test/image\aachen_000000_000019.png 

test/image\aachen_000001_000019.png 

test/image\aachen_000002_000019.png 

test/image\aachen_000003_000019.png 

test/image\aachen_000004_000019.png 

test/image\aachen_000005_000019.png 

test/augmented\image_original_aachen_000000_000019.png_6ffb9fec-f80a-4a02-9e34-d36065d5b5ff.png 

test/augmented\image_original_aachen_000001_000019.png_011653eb-8368-4895-90f6-ba0ed7dbeed8.png 

test/augmented\image_original_aachen_000001_000019.png_56e8642c-ec1f-4c7d-89e5-d931d8ce05f3.png 

test/augmented\image_original_aachen_000001_000019.png_90464c97-3175-4b4b-be49-441e52fcbb03.png 

test/augmented\image_original_aachen_000001_000019.png_9d45ce92-457c-4e92-b147-af0606a91cdf.png 

test/augmented\image_original_aachen_000001_000019.png_fa216f30-27e3-4c4e-a749-1baa59af743e.png 

test/augmented\image_original_aachen_000002_000019.png_7c4ec104-c8ef-4fda-af2a-a94174c3955b.png 

test/augmented\image_original_aachen_000002_000019.png_884c824e-0ad3-4203-ab51-34d9e6e

In [30]:
print(mask_list)

['test/mask\\aachen_000000_000019.png', 'test/mask\\aachen_000001_000019.png', 'test/mask\\aachen_000002_000019.png', 'test/mask\\aachen_000003_000019.png', 'test/mask\\aachen_000004_000019.png', 'test/mask\\aachen_000005_000019.png', 'test/mask\\aachen_000006_000019.png', 'test/mask\\aachen_000007_000019.png', 'test/mask\\aachen_000008_000019.png', 'test/mask\\aachen_000009_000019.png', 'test/mask\\aachen_000010_000019.png', 'test/mask\\aachen_000011_000019.png', 'test/mask\\aachen_000012_000019.png', 'test/mask\\aachen_000013_000019.png', 'test/mask\\aachen_000014_000019.png', 'test/mask\\aachen_000015_000019.png', 'test/mask\\aachen_000016_000019.png', 'test/mask\\aachen_000017_000019.png', 'test/mask\\aachen_000018_000019.png', 'test/mask\\aachen_000019_000019.png', 'test/mask\\aachen_000020_000019.png', 'test/mask\\aachen_000021_000019.png', 'test/mask\\aachen_000022_000019.png', 'test/mask\\aachen_000023_000019.png', 'test/mask\\aachen_000024_000019.png', 'test/mask\\aachen_00002

In [22]:
print(image_list)

['test/image\\aachen_000000_000019.png', 'test/image\\aachen_000001_000019.png', 'test/image\\aachen_000002_000019.png', 'test/image\\aachen_000003_000019.png', 'test/image\\aachen_000004_000019.png', 'test/image\\aachen_000005_000019.png', 'test/image\\aachen_000006_000019.png', 'test/image\\aachen_000007_000019.png', 'test/image\\aachen_000008_000019.png', 'test/image\\aachen_000009_000019.png', 'test/image\\aachen_000010_000019.png', 'test/image\\aachen_000011_000019.png', 'test/image\\aachen_000012_000019.png', 'test/image\\aachen_000013_000019.png', 'test/image\\aachen_000014_000019.png', 'test/image\\aachen_000015_000019.png', 'test/image\\aachen_000016_000019.png', 'test/image\\aachen_000017_000019.png', 'test/image\\aachen_000018_000019.png', 'test/image\\aachen_000019_000019.png', 'test/image\\aachen_000020_000019.png', 'test/image\\aachen_000021_000019.png', 'test/image\\aachen_000022_000019.png', 'test/image\\aachen_000023_000019.png', 'test/image\\aachen_000024_000019.png',

In [31]:
# sanity check
for i in range(len(image_list)):
    assert image_list[i] == mask_list[i]
print(image_list[2], mask_list[2])

AssertionError: 